---
name: Nginx Proxy Manager
version: dev
slug: nginxproxymanager
description: Manage Nginx proxy hosts with a simple, powerful interface
url: https://github.com/GraysonCAdams/addon-nginx-proxy-manager
ingress: true
ingress_port: 81
ingress_stream: true
panel_icon: mdi:nginx
panel_title: Nginx Proxy Manager
startup: services
init: false
arch:
  - aarch64
  - amd64
  - armv7
hassio_api: true
ports:
  80/tcp: 80
  81/tcp: null
  443/tcp: 443
ports_description:
  80/tcp: HTTP traffic for reverse proxy
  81/tcp: Admin web interface (optional, ingress preferred)
  443/tcp: HTTPS/SSL traffic for reverse proxy
map:
  - addon_config:rw
backup_exclude:
  - "*/logs"
